# Default values for mapserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfs:
  data:
    pvcname: pvc-qwc-data
    pvname: pv-qwc-data
    server: 10.236.1.22
    path: /home/aborghi/Documents/support/sersa/nfs/volumes
    storage: 10Gi

idstuff: &idstuff
  SERVICE_UID:
    value: 1012
  SERVICE_GID:
    value: 1012

qwcservices:
  config:
    pg:
      conf: |
        [qwc_configdb]
        host=10.236.1.22
        port=5439
        dbname=qwc_demo
        user=qwc_admin
        password=qwc_admin
        sslmode=disable

        [qwc_geodb]
        host=10.236.1.22
        port=5439
        dbname=qwc_demo
        user=qwc_service
        password=qwc_service
        sslmode=disable
  qgis:
    ingress:
      enabled: false
    securityContext: &qgissecurity
      runAsNonRoot: true
      runAsUser: 1012
      runAsGroup: 0
    podSecurityContext:
      <<: *qgissecurity
      fsGroup: 1012

  qwc:
    ingress:
      enabled: true
      hostGroups:
        host1:
          tls:
            enabled: false
            secretName: 'my-tls-secret'
          hosts:
            - qwc.local
    securityContext: &security
      runAsNonRoot: true
      runAsUser: 1012
      runAsGroup: 1012
    podSecurityContext:
      <<: *security
      fsGroup: 1012

    services:
      admin-gui:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      auth-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      config-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      data-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      document-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      elevation-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      feature-info-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      fulltext-search-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      mapinfo-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      map-viewer:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      ogc-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      permalink-service:
        containers:
          uwsgi:
            env:
              <<: *idstuff
      solr:
        containers:
          uwsgi:
            env:
              <<: *idstuff
